import { connectDB } from './connection';
import { Product } from './models/Product';
import { Category } from './models/Category';

const CATEGORY_FOLDER_BY_ID: Record<string, string> = {
  Vitaminas: 'vitaminas',
  'Cuidado personal': 'cuidado-personal',
  'Cuidado del bebé': 'cuidado-bebe',
  Suplementos: 'suplementos',
  'Salud de la piel': 'salud-piel',
  Fitness: 'fitness',
  Medicamentos: 'medicamentos',
  Hidratantes: 'hidratantes',
  Fragancias: 'fragancias',
  Maquillaje: 'maquillaje',
};

const PRODUCTS = [
  // VITAMINAS
  {
    id: 'nature-made-vitamin-d3-5000-iu',
    name: 'Vitamin D3 5000 IU Softgels',
    brand: 'Nature Made',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 11.99,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 2340,
    short: 'Vitamina D3 de alta potencia para apoyo diario.',
    benefits: ['Salud osea', 'Soporte inmune', 'Uso diario'],
    usage: 'Tomar 1 softgel al dia con comida.',
    ingredients: 'Vitamina D3, aceite de soya, gelatina, glicerina.',
    warnings: 'Consulte a su medico si esta embarazada o en tratamiento.',
    stock: 85,
    color: 'oklch(0.92 0.03 75)',
    swatchColor: 'oklch(0.75 0.14 65)',
    label: 'Nature Made\nD3 5000 IU',
  },
  {
    id: 'centrum-women-multivitamin',
    name: 'Women Multivitamin Tablets',
    brand: 'Centrum',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 20.73,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 1250,
    short: 'Multivitaminico diario formulado para mujeres adultas.',
    benefits: ['Rutina diaria', 'Vitaminas esenciales', 'Apoyo general'],
    usage: 'Tomar 1 tableta al dia con alimentos.',
    ingredients: 'Mezcla de vitaminas y minerales esenciales.',
    warnings: 'No exceder la porcion recomendada.',
    stock: 64,
    color: 'oklch(0.93 0.03 20)',
    swatchColor: 'oklch(0.73 0.15 20)',
    label: 'Centrum\nWomen',
  },
  {
    id: 'natures-way-alive-womens-ultra',
    name: "Alive! Women's Ultra Multivitamin",
    brand: "Nature's Way",
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 23.40,
    rating: 4.7,
    reviews: 396,
    short: 'Formula completa con vitaminas, minerales y alimentos verdes.',
    benefits: ['Energia diaria', 'Complejo B', 'Soporte nutricional'],
    usage: 'Tomar 1 tableta al dia preferiblemente con comida.',
    ingredients: 'Vitaminas, minerales y mezcla de frutas y vegetales.',
    warnings: 'Mantener fuera del alcance de los ninos.',
    stock: 41,
    color: 'oklch(0.90 0.05 135)',
    swatchColor: 'oklch(0.58 0.14 140)',
    label: 'Alive!\nWomen',
  },
  {
    id: 'now-foods-methyl-b12-1000-mcg',
    name: 'Methyl B-12 1000 mcg Lozenges',
    brand: 'NOW Foods',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 12.99,
    tag: 'Nuevo',
    rating: 4.6,
    reviews: 890,
    short: 'Vitamina B12 sublingual para energia y metabolismo.',
    benefits: ['Metabolismo energetico', 'B12 sublingual', 'Facil uso'],
    usage: 'Tomar 1 pastilla al dia y dejar disolver en la boca.',
    ingredients: 'Metilcobalamina, xilitol, celulosa, sabor natural.',
    warnings: 'Consultar al medico antes de usar durante embarazo.',
    stock: 67,
    color: 'oklch(0.93 0.02 220)',
    swatchColor: 'oklch(0.60 0.10 235)',
    label: 'NOW\nB-12',
  },
  {
    id: 'garden-of-life-vitamin-code-women',
    name: 'Vitamin Code Women Whole Food Multivitamin',
    brand: 'Garden of Life',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 40.54,
    tag: 'Premium',
    rating: 4.7,
    reviews: 1041,
    short: 'Multivitaminico integral con base de alimentos reales.',
    benefits: ['Whole food', 'Vitaminas y minerales', 'Uso diario'],
    usage: 'Tomar 2 capsulas al dia con comida.',
    ingredients: 'Vitaminas, minerales y blend de frutas y vegetales.',
    warnings: 'No usar si el sello de seguridad esta roto.',
    stock: 29,
    color: 'oklch(0.89 0.04 150)',
    swatchColor: 'oklch(0.50 0.11 155)',
    label: 'Vitamin Code\nWomen',
  },

  // SUPLEMENTOS
  {
    id: 'nordic-naturals-ultimate-omega',
    name: 'Ultimate Omega Soft Gels',
    brand: 'Nordic Naturals',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 26.62,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 890,
    short: 'Omega-3 premium con EPA y DHA para corazon y cerebro.',
    benefits: ['Corazon', 'Cerebro', 'Omega-3 premium'],
    usage: 'Tomar 2 softgels al dia con alimentos.',
    ingredients: 'Aceite de pescado purificado, gelatina, glicerina.',
    warnings: 'Contiene derivados de pescado.',
    stock: 58,
    color: 'oklch(0.88 0.04 75)',
    swatchColor: 'oklch(0.70 0.14 65)',
    label: 'Ultimate\nOmega',
  },
  {
    id: 'vital-proteins-collagen-peptides',
    name: 'Collagen Peptides Unflavored 20 oz',
    brand: 'Vital Proteins',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 56.40,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 713,
    short: 'Colageno hidrolizado sin sabor para rutina diaria.',
    benefits: ['Colageno', 'Mezcla facil', 'Uso diario'],
    usage: 'Agregar 1 o 2 scoops a agua, cafe o smoothie.',
    ingredients: 'Peptidos de colageno bovino.',
    warnings: 'Producto derivado de bovino.',
    stock: 36,
    color: 'oklch(0.94 0.02 85)',
    swatchColor: 'oklch(0.84 0.04 85)',
    label: 'Vital\nCollagen',
  },
  {
    id: 'sports-research-creatine-monohydrate',
    name: 'Creatine Monohydrate Unflavored 300 g',
    brand: 'Sports Research',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 24.34,
    rating: 4.9,
    reviews: 1347,
    short: 'Creatina monohidratada sin sabor para rendimiento.',
    benefits: ['Fuerza', 'Rendimiento', 'Facil mezcla'],
    usage: 'Mezclar 1 scoop al dia con agua o bebida favorita.',
    ingredients: 'Creatina monohidratada.',
    warnings: 'Mantener una adecuada hidratacion.',
    stock: 72,
    color: 'oklch(0.90 0.04 115)',
    swatchColor: 'oklch(0.60 0.14 115)',
    label: 'Sports Research\nCreatine',
  },
  {
    id: 'garden-of-life-once-daily-womens-probiotic',
    name: "Dr. Formulated Probiotics Once Daily Women's",
    brand: 'Garden of Life',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 36.79,
    rating: 4.7,
    reviews: 644,
    short: 'Probiotico diario de alta potencia para salud digestiva.',
    benefits: ['Digestion', 'Uso diario', '50 billion CFU'],
    usage: 'Tomar 1 capsula al dia con o sin comida.',
    ingredients: 'Mezcla de probioticos y fibra prebiotica.',
    warnings: 'Guardar en lugar fresco y seco.',
    stock: 44,
    color: 'oklch(0.92 0.02 140)',
    swatchColor: 'oklch(0.60 0.06 150)',
    label: 'Women\nProbiotic',
  },
  {
    id: 'nuun-sport-hydration-strawberry-lemonade',
    name: 'Sport Hydration Tablets Strawberry Lemonade',
    brand: 'Nuun',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 7.44,
    tag: 'Nuevo',
    rating: 4.7,
    reviews: 1098,
    short: 'Tabletas efervescentes con electrolitos para hidratacion.',
    benefits: ['Hidratacion', 'Electrolitos', 'Facil llevar'],
    usage: 'Disolver 1 tableta en agua segun necesidad.',
    ingredients: 'Electrolitos, sodio, potasio, magnesio.',
    warnings: 'No sustituye una dieta balanceada.',
    stock: 93,
    color: 'oklch(0.95 0.04 80)',
    swatchColor: 'oklch(0.72 0.15 75)',
    label: 'Nuun Sport\nHydration',
  },

  // SALUD DE LA PIEL
  {
    id: 'differin-adapalene-gel-0-1',
    name: 'Adapalene Gel 0.1% Acne Treatment',
    brand: 'Differin',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 20.20,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 863,
    short: 'Tratamiento topico con adapaleno para acne.',
    benefits: ['Acne', 'Uso nocturno', 'Textura'],
    usage: 'Aplicar una capa fina por la noche en piel limpia.',
    ingredients: 'Adapalene 0.1%.',
    warnings: 'Usar protector solar durante el dia.',
    stock: 48,
    color: 'oklch(0.93 0.03 45)',
    swatchColor: 'oklch(0.65 0.15 45)',
    label: 'Differin\nGel',
  },
  {
    id: 'panoxyl-acne-foaming-wash',
    name: 'Acne Foaming Wash Maximum Strength',
    brand: 'PanOxyl',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 7.69,
    rating: 4.6,
    reviews: 1314,
    short: 'Limpiador para piel propensa al acne.',
    benefits: ['Limpieza profunda', 'Acne', 'Uso diario'],
    usage: 'Aplicar sobre piel humeda, masajear y enjuagar.',
    ingredients: 'Benzoyl peroxide y base limpiadora.',
    warnings: 'Puede resecar o decolorar telas.',
    stock: 76,
    color: 'oklch(0.94 0.03 60)',
    swatchColor: 'oklch(0.74 0.12 58)',
    label: 'PanOxyl\nWash',
  },
  {
    id: 'panoxyl-clarifying-exfoliant-2-salicylic-acid',
    name: 'Clarifying Exfoliant 2% Salicylic Acid',
    brand: 'PanOxyl',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 14.69,
    rating: 4.6,
    reviews: 1303,
    short: 'Exfoliante quimico para piel con imperfecciones.',
    benefits: ['Poros', 'Textura', 'Acido salicilico'],
    usage: 'Aplicar con algodon o manos sobre piel limpia.',
    ingredients: 'Acido salicilico 2%.',
    warnings: 'Introducir gradualmente y usar SPF.',
    stock: 53,
    color: 'oklch(0.90 0.04 25)',
    swatchColor: 'oklch(0.62 0.14 28)',
    label: 'PanOxyl\n2% BHA',
  },
  {
    id: 'the-ordinary-retinol-0-5-in-squalane',
    name: 'Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 9.90,
    tag: 'Best seller',
    rating: 4.5,
    reviews: 1256,
    short: 'Serum de retinol en escualano para rutina nocturna.',
    benefits: ['Retinol', 'Escualano', 'Presupuesto accesible'],
    usage: 'Aplicar por la noche despues de limpiar la piel.',
    ingredients: 'Retinol 0.5%, escualano.',
    warnings: 'Introducir poco a poco y usar protector solar.',
    stock: 91,
    color: 'oklch(0.94 0.02 50)',
    swatchColor: 'oklch(0.70 0.08 50)',
    label: 'The Ordinary\nRetinol',
  },
  {
    id: 'the-ordinary-hyaluronic-acid-2-b5',
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 9.90,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 1543,
    short: 'Serum hidratante con acido hialuronico y vitamina B5.',
    benefits: ['Hidratacion', 'Plumping', 'Uso diario'],
    usage: 'Aplicar sobre piel humeda antes de la crema.',
    ingredients: 'Acido hialuronico, vitamina B5.',
    warnings: 'Uso externo.',
    stock: 112,
    color: 'oklch(0.93 0.02 200)',
    swatchColor: 'oklch(0.80 0.06 210)',
    label: 'HA 2%\n+ B5',
  },

  // HIDRATANTES
  {
    id: 'cerave-moisturizing-cream',
    name: 'Moisturizing Cream 340 g',
    brand: 'CeraVe',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 16.99,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 4567,
    short: 'Crema con ceramidas para piel seca y muy seca.',
    benefits: ['Ceramidas', 'Hidratacion 24h', 'No comedogenica'],
    usage: 'Aplicar segun necesidad en rostro y cuerpo.',
    ingredients: 'Ceramidas, acido hialuronico, glicerina.',
    warnings: 'Solo uso externo.',
    stock: 88,
    color: 'oklch(0.96 0.01 85)',
    swatchColor: 'oklch(0.92 0.015 85)',
    label: 'CeraVe\nCream',
  },
  {
    id: 'cerave-pm-facial-moisturizing-lotion',
    name: 'PM Facial Moisturizing Lotion',
    brand: 'CeraVe',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 19.99,
    rating: 4.6,
    reviews: 892,
    short: 'Locion ligera de noche con niacinamida y ceramidas.',
    benefits: ['Noche', 'Ligera', 'Niacinamida'],
    usage: 'Aplicar por la noche sobre rostro limpio.',
    ingredients: 'Niacinamida, ceramidas, acido hialuronico.',
    warnings: 'Evitar contacto con los ojos.',
    stock: 57,
    color: 'oklch(0.95 0.012 90)',
    swatchColor: 'oklch(0.88 0.018 90)',
    label: 'CeraVe\nPM',
  },
  {
    id: 'la-roche-posay-toleriane-double-repair',
    name: 'Toleriane Double Repair Face Moisturizer',
    brand: 'La Roche-Posay',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 24.99,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 2589,
    short: 'Hidratante diario para barrera cutanea sensible.',
    benefits: ['Barrera', 'Piel sensible', 'Uso diario'],
    usage: 'Aplicar manana y noche sobre rostro limpio.',
    ingredients: 'Ceramida-3, niacinamida, glicerina.',
    warnings: 'Uso externo.',
    stock: 46,
    color: 'oklch(0.94 0.02 200)',
    swatchColor: 'oklch(0.70 0.08 210)',
    label: 'Toleriane\nRepair',
  },
  {
    id: 'neutrogena-hydro-boost-water-gel',
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 18.99,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 1234,
    short: 'Gel hidratante ligero con textura acuosa.',
    benefits: ['Ligera', 'Oil free', 'Acido hialuronico'],
    usage: 'Aplicar por la manana o noche sobre el rostro.',
    ingredients: 'Acido hialuronico, glicerina.',
    warnings: 'Solo uso externo.',
    stock: 69,
    color: 'oklch(0.93 0.03 185)',
    swatchColor: 'oklch(0.75 0.08 195)',
    label: 'Hydro\nBoost',
  },
  {
    id: 'cetaphil-moisturizing-cream',
    name: 'Moisturizing Cream Fragrance Free',
    brand: 'Cetaphil',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 7.74,
    rating: 4.7,
    reviews: 1130,
    short: 'Crema clasica para piel seca y sensible.',
    benefits: ['Piel sensible', 'Sin fragancia', 'Hidratacion'],
    usage: 'Aplicar segun necesidad en rostro o cuerpo.',
    ingredients: 'Humectantes y emolientes para piel seca.',
    warnings: 'Uso externo.',
    stock: 75,
    color: 'oklch(0.95 0.02 70)',
    swatchColor: 'oklch(0.86 0.04 70)',
    label: 'Cetaphil\nCream',
  },

  // CUIDADO DEL BEBE
  {
    id: 'aquaphor-baby-healing-ointment',
    name: 'Baby Healing Ointment',
    brand: 'Aquaphor',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 21.64,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 679,
    short: 'Pomada protectora para resequedad y rozaduras.',
    benefits: ['Barrera protectora', 'Piel delicada', 'Sin fragancia'],
    usage: 'Aplicar una capa fina sobre la zona necesaria.',
    ingredients: 'Petrolatum, pantenol, glicerina.',
    warnings: 'Solo uso externo.',
    stock: 47,
    color: 'oklch(0.95 0.02 85)',
    swatchColor: 'oklch(0.86 0.04 85)',
    label: 'Aquaphor\nBaby',
  },
  {
    id: 'aveeno-baby-daily-moisture-lotion',
    name: 'Baby Daily Moisture Lotion',
    brand: 'Aveeno Baby',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 14.82,
    rating: 4.7,
    reviews: 479,
    short: 'Locion con avena para piel delicada del bebe.',
    benefits: ['Avena', 'Uso diario', 'Sin fragancia'],
    usage: 'Aplicar despues del bano o segun necesidad.',
    ingredients: 'Avena prebiotica, emolientes, humectantes.',
    warnings: 'Evitar contacto con los ojos.',
    stock: 58,
    color: 'oklch(0.95 0.02 75)',
    swatchColor: 'oklch(0.84 0.05 75)',
    label: 'Aveeno\nBaby',
  },
  {
    id: 'cetaphil-baby-daily-lotion',
    name: 'Baby Daily Lotion',
    brand: 'Cetaphil Baby',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 13.72,
    rating: 4.6,
    reviews: 920,
    short: 'Locion suave para hidratacion diaria del bebe.',
    benefits: ['Hidratacion', 'Piel delicada', 'Uso diario'],
    usage: 'Aplicar sobre la piel limpia y seca.',
    ingredients: 'Mezcla humectante suave para bebe.',
    warnings: 'Solo uso topico.',
    stock: 51,
    color: 'oklch(0.96 0.01 90)',
    swatchColor: 'oklch(0.90 0.02 90)',
    label: 'Cetaphil\nBaby',
  },
  {
    id: 'cerave-baby-moisturizing-cream',
    name: 'Baby Moisturizing Cream',
    brand: 'CeraVe Baby',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 12.49,
    rating: 4.8,
    reviews: 389,
    short: 'Crema para bebe con ceramidas y acido hialuronico.',
    benefits: ['Ceramidas', '24h hidratacion', 'Sin fragancia'],
    usage: 'Aplicar segun necesidad en piel limpia.',
    ingredients: 'Ceramidas, acido hialuronico, glicerina.',
    warnings: 'Uso externo.',
    stock: 54,
    color: 'oklch(0.96 0.01 95)',
    swatchColor: 'oklch(0.91 0.02 95)',
    label: 'CeraVe\nBaby',
  },
  {
    id: 'desitin-maximum-strength-diaper-rash',
    name: 'Maximum Strength Diaper Rash Paste',
    brand: 'Desitin',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 7.97,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 1234,
    short: 'Pasta con oxido de zinc para irritacion del panal.',
    benefits: ['Oxido de zinc', 'Proteccion', 'Rozaduras'],
    usage: 'Aplicar en cada cambio de panal sobre piel limpia.',
    ingredients: 'Oxido de zinc 40%.',
    warnings: 'Solo uso externo.',
    stock: 79,
    color: 'oklch(0.95 0.015 75)',
    swatchColor: 'oklch(0.88 0.03 75)',
    label: 'Desitin\nRash',
  },

  // FITNESS
  {
    id: 'optimum-nutrition-gold-standard-whey',
    name: 'Gold Standard 100% Whey Protein',
    brand: 'Optimum Nutrition',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 39.99,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 2749,
    short: 'Proteina whey clasica para recuperacion post entrenamiento.',
    benefits: ['Proteina', 'Recuperacion', 'Mezcla facil'],
    usage: 'Mezclar 1 scoop con agua o leche despues de entrenar.',
    ingredients: 'Whey protein blend, sabor natural y lecitina.',
    warnings: 'Contiene leche.',
    stock: 62,
    color: 'oklch(0.90 0.04 55)',
    swatchColor: 'oklch(0.55 0.12 55)',
    label: 'ON\nWhey',
  },
  {
    id: 'optimum-nutrition-amino-energy',
    name: 'Essential Amino Energy',
    brand: 'Optimum Nutrition',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 41.99,
    rating: 4.6,
    reviews: 2100,
    short: 'Aminoacidos con cafeina para energia pre entreno.',
    benefits: ['Energia', 'Aminoacidos', 'Pre workout'],
    usage: 'Mezclar en agua antes del entrenamiento.',
    ingredients: 'Amino blend, extracto de te verde, cafeina.',
    warnings: 'Contiene cafeina.',
    stock: 38,
    color: 'oklch(0.90 0.05 145)',
    swatchColor: 'oklch(0.52 0.10 155)',
    label: 'Amino\nEnergy',
  },
  {
    id: 'bsn-syntha-6',
    name: 'SYNTHA-6 Protein Powder',
    brand: 'BSN',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 55.00,
    tag: 'Premium',
    rating: 4.7,
    reviews: 1800,
    short: 'Blend de proteinas para batidos densos y recuperacion.',
    benefits: ['Proteina blend', 'Sabor', 'Recuperacion'],
    usage: 'Mezclar 1 scoop con agua o leche.',
    ingredients: 'Proteinas de suero y caseina, saborizantes.',
    warnings: 'Contiene leche y soya.',
    stock: 31,
    color: 'oklch(0.88 0.05 35)',
    swatchColor: 'oklch(0.50 0.12 35)',
    label: 'BSN\nSYNTHA-6',
  },
  {
    id: 'cellucor-c4-original-pre-workout',
    name: 'C4 Original Pre-Workout Powder',
    brand: 'Cellucor',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 29.99,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 3200,
    short: 'Pre entreno clasico para energia y enfoque.',
    benefits: ['Pre workout', 'Energia', 'Enfoque'],
    usage: 'Mezclar 1 scoop con agua 20 a 30 minutos antes de entrenar.',
    ingredients: 'Beta-alanina, cafeina, creatina nitrato.',
    warnings: 'Contiene cafeina y puede causar hormigueo.',
    stock: 70,
    color: 'oklch(0.92 0.05 65)',
    swatchColor: 'oklch(0.65 0.13 60)',
    label: 'C4\nOriginal',
  },
  {
    id: 'muscle-milk-genuine-protein-shake',
    name: 'Genuine Protein Shake Vanilla Creme',
    brand: 'Muscle Milk',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 57.01,
    rating: 4.6,
    reviews: 1600,
    short: 'Batido listo para tomar con alto contenido de proteina.',
    benefits: ['Listo para tomar', 'Proteina', 'Conveniencia'],
    usage: 'Consumir frio como snack o post entrenamiento.',
    ingredients: 'Mezcla proteica lactea, vitaminas y minerales.',
    warnings: 'Contiene leche.',
    stock: 25,
    color: 'oklch(0.94 0.02 80)',
    swatchColor: 'oklch(0.80 0.05 80)',
    label: 'Muscle Milk\nShake',
  },

  // MEDICAMENTOS
  {
    id: 'tylenol-extra-strength-caplets',
    name: 'Extra Strength Pain Relief Caplets 500 mg',
    brand: 'Tylenol',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 10.97,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 1567,
    short: 'Analgesico de acetaminofen para dolor y fiebre.',
    benefits: ['Dolor', 'Fiebre', 'Uso comun'],
    usage: 'Seguir instrucciones del empaque para adultos.',
    ingredients: 'Acetaminofen 500 mg.',
    warnings: 'No exceder la dosis indicada. Riesgo hepatico.',
    stock: 108,
    color: 'oklch(0.94 0.02 45)',
    swatchColor: 'oklch(0.65 0.08 45)',
    label: 'Tylenol\n500 mg',
  },
  {
    id: 'advil-ibuprofen-200-mg',
    name: 'Ibuprofen 200 mg Coated Caplets',
    brand: 'Advil',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 9.59,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 2341,
    short: 'Ibuprofeno para dolor, fiebre e inflamacion.',
    benefits: ['Dolor', 'Fiebre', 'Inflamacion'],
    usage: 'Seguir instrucciones del empaque y tomar con agua.',
    ingredients: 'Ibuprofeno 200 mg.',
    warnings: 'Tomar con alimentos si causa molestia estomacal.',
    stock: 124,
    color: 'oklch(0.93 0.02 200)',
    swatchColor: 'oklch(0.60 0.10 235)',
    label: 'Advil\n200 mg',
  },
  {
    id: 'zyrtec-allergy-tablets',
    name: '24 Hour Allergy Relief Tablets',
    brand: 'Zyrtec',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 22.65,
    rating: 4.8,
    reviews: 980,
    short: 'Cetirizina para sintomas comunes de alergia.',
    benefits: ['Alergia', '24 horas', 'Uso diario'],
    usage: 'Usar segun las instrucciones del empaque.',
    ingredients: 'Cetirizine HCl 10 mg.',
    warnings: 'Puede causar somnolencia.',
    stock: 66,
    color: 'oklch(0.91 0.03 200)',
    swatchColor: 'oklch(0.55 0.08 235)',
    label: 'Zyrtec\n24H',
  },
  {
    id: 'mucinex-dm-12hr-maximum-strength',
    name: 'DM 12Hr Maximum Strength Tablets',
    brand: 'Mucinex',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 17.50,
    rating: 4.8,
    reviews: 740,
    short: 'Alivio de tos y congestion en formato de 12 horas.',
    benefits: ['Congestion', 'Tos', '12 horas'],
    usage: 'Seguir indicaciones del empaque para adultos.',
    ingredients: 'Dextromethorphan HBr, guaifenesin.',
    warnings: 'No usar junto a otros medicamentos similares.',
    stock: 52,
    color: 'oklch(0.92 0.04 130)',
    swatchColor: 'oklch(0.58 0.10 140)',
    label: 'Mucinex\nDM',
  },
  {
    id: 'pepto-bismol-original-liquid',
    name: 'Original Liquid Upset Stomach Relief',
    brand: 'Pepto Bismol',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 5.47,
    rating: 4.8,
    reviews: 1120,
    short: 'Liquido para malestar estomacal y nausea.',
    benefits: ['Malestar estomacal', 'Nausea', 'Indigestion'],
    usage: 'Usar segun las instrucciones del empaque.',
    ingredients: 'Bismuth subsalicylate.',
    warnings: 'No usar si es alergico a salicilatos.',
    stock: 97,
    color: 'oklch(0.93 0.05 355)',
    swatchColor: 'oklch(0.63 0.15 355)',
    label: 'Pepto\nLiquid',
  },

  // CUIDADO PERSONAL
  {
    id: 'dove-deep-moisture-body-wash',
    name: 'Deep Moisture Body Wash',
    brand: 'Dove',
    category: 'Cuidado personal',
    need: 'Piel seca',
    price: 10.97,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 2200,
    short: 'Gel de bano humectante para uso diario.',
    benefits: ['Limpieza', 'Hidratacion', 'Uso diario'],
    usage: 'Aplicar sobre piel humeda y enjuagar.',
    ingredients: 'Base limpiadora suave y agentes humectantes.',
    warnings: 'Evitar contacto con los ojos.',
    stock: 83,
    color: 'oklch(0.95 0.02 85)',
    swatchColor: 'oklch(0.86 0.03 85)',
    label: 'Dove\nBody Wash',
  },
  {
    id: 'native-coconut-vanilla-deodorant',
    name: 'Coconut & Vanilla Deodorant',
    brand: 'Native',
    category: 'Cuidado personal',
    need: 'Piel seca',
    price: 13.97,
    rating: 4.4,
    reviews: 1100,
    short: 'Desodorante sin aluminio con aroma coco vainilla.',
    benefits: ['Sin aluminio', 'Uso diario', 'Aroma suave'],
    usage: 'Aplicar sobre axilas limpias y secas.',
    ingredients: 'Base desodorante con aceites y ceras.',
    warnings: 'Suspender si aparece irritacion.',
    stock: 48,
    color: 'oklch(0.94 0.03 95)',
    swatchColor: 'oklch(0.72 0.07 95)',
    label: 'Native\nDeo',
  },
  {
    id: 'colgate-total-clean-mint-toothpaste',
    name: 'Total Clean Mint Toothpaste',
    brand: 'Colgate',
    category: 'Cuidado personal',
    need: 'Energía y vitaminas',
    price: 9.22,
    rating: 4.8,
    reviews: 900,
    short: 'Pasta dental para limpieza diaria y aliento fresco.',
    benefits: ['Cuidado oral', 'Menta', 'Uso diario'],
    usage: 'Cepillar dientes dos veces al dia.',
    ingredients: 'Fluoruro estannoso y agentes limpiadores.',
    warnings: 'No ingerir.',
    stock: 102,
    color: 'oklch(0.93 0.03 180)',
    swatchColor: 'oklch(0.65 0.08 190)',
    label: 'Colgate\nTotal',
  },
  {
    id: 'listerine-cool-mint-mouthwash',
    name: 'Cool Mint Antiseptic Mouthwash',
    brand: 'Listerine',
    category: 'Cuidado personal',
    need: 'Energía y vitaminas',
    price: 6.98,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 3456,
    short: 'Enjuague bucal antiseptico con sabor menta.',
    benefits: ['Higiene oral', 'Aliento fresco', 'Rutina diaria'],
    usage: 'Enjuagar por 30 segundos y escupir.',
    ingredients: 'Activos antisepticos y sabor menta.',
    warnings: 'No tragar.',
    stock: 136,
    color: 'oklch(0.90 0.03 160)',
    swatchColor: 'oklch(0.55 0.06 170)',
    label: 'Listerine\nMint',
  },
  {
    id: 'gillette-fusion5-razor',
    name: 'Fusion5 Razor Handle + 1 Refill',
    brand: 'Gillette',
    category: 'Cuidado personal',
    need: 'Energía y vitaminas',
    price: 12.29,
    rating: 4.7,
    reviews: 840,
    short: 'Rasuradora manual para afeitado diario.',
    benefits: ['Afeitado', 'Precision', 'Uso personal'],
    usage: 'Usar con espuma o gel de afeitar.',
    ingredients: 'Mango y cartucho de hojas Fusion5.',
    warnings: 'Manipular con cuidado.',
    stock: 61,
    color: 'oklch(0.91 0.03 220)',
    swatchColor: 'oklch(0.56 0.07 230)',
    label: 'Gillette\nFusion5',
  },

  // FRAGANCIAS
  {
    id: 'dior-sauvage-eau-de-toilette',
    name: 'Sauvage Eau de Toilette',
    brand: 'Dior',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 130.97,
    tag: 'Best seller',
    rating: 4.5,
    reviews: 980,
    short: 'Fragancia masculina fresca y especiada muy conocida.',
    benefits: ['Aroma intenso', 'Uso nocturno', 'Iconico'],
    usage: 'Aplicar en puntos de pulso.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable. Solo uso externo.',
    stock: 19,
    color: 'oklch(0.86 0.02 250)',
    swatchColor: 'oklch(0.38 0.05 250)',
    label: 'Dior\nSauvage',
  },
  {
    id: 'versace-bright-crystal-eau-de-toilette',
    name: 'Bright Crystal Eau de Toilette',
    brand: 'Versace',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 59.00,
    rating: 4.7,
    reviews: 720,
    short: 'Fragancia floral fresca de gran popularidad.',
    benefits: ['Floral', 'Ligera', 'Uso diario'],
    usage: 'Aplicar en cuello y munecas.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Evitar ojos y fuego directo.',
    stock: 28,
    color: 'oklch(0.92 0.04 5)',
    swatchColor: 'oklch(0.73 0.12 10)',
    label: 'Versace\nBright Crystal',
  },
  {
    id: 'victorias-secret-bombshell-eau-de-parfum',
    name: 'Bombshell Eau de Parfum',
    brand: "Victoria's Secret",
    category: 'Fragancias',
    need: 'Piel seca',
    price: 94.99,
    rating: 4.6,
    reviews: 640,
    short: 'Perfume femenino frutal floral de la linea Bombshell.',
    benefits: ['Frutal floral', 'Femenina', 'Popular'],
    usage: 'Aplicar en puntos de pulso.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable. Solo uso externo.',
    stock: 21,
    color: 'oklch(0.93 0.05 345)',
    swatchColor: 'oklch(0.68 0.15 345)',
    label: 'Bombshell\nEDP',
  },
  {
    id: 'sol-de-janeiro-cheirosa-62-mist',
    name: "Brazilian Crush Cheirosa 62 Hair & Body Fragrance Mist",
    brand: 'Sol de Janeiro',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 38.00,
    tag: 'Best seller',
    rating: 4.8,
    reviews: 1500,
    short: 'Mist gourmand con aroma caracteristico de la marca.',
    benefits: ['Body mist', 'Aroma dulce', 'Ligera'],
    usage: 'Rociar sobre cuerpo o cabello a distancia.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable. No usar cerca del fuego.',
    stock: 35,
    color: 'oklch(0.94 0.05 80)',
    swatchColor: 'oklch(0.72 0.14 75)',
    label: 'Cheirosa\n62',
  },
  {
    id: 'ariana-grande-cloud-eau-de-parfum',
    name: 'Cloud Eau de Parfum',
    brand: 'Ariana Grande',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 68.00,
    rating: 4.7,
    reviews: 890,
    short: 'Perfume dulce y cremoso muy popular en retail.',
    benefits: ['Dulce', 'Uso diario', 'Muy conocido'],
    usage: 'Aplicar en cuello y munecas.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Solo uso externo. Inflamable.',
    stock: 24,
    color: 'oklch(0.94 0.02 235)',
    swatchColor: 'oklch(0.74 0.06 235)',
    label: 'Cloud\nEDP',
  },

  // MAQUILLAJE
  {
    id: 'maybelline-sky-high-mascara',
    name: 'Lash Sensational Sky High Mascara',
    brand: 'Maybelline',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 10.82,
    tag: 'Best seller',
    rating: 4.5,
    reviews: 2500,
    short: 'Mascara de gran alargamiento muy popular.',
    benefits: ['Alargamiento', 'Volumen', 'Uso diario'],
    usage: 'Aplicar desde la raiz hacia las puntas.',
    ingredients: 'Base cosmetica para pestanas y pigmentos.',
    warnings: 'No compartir maquillaje de ojos.',
    stock: 94,
    color: 'oklch(0.92 0.03 20)',
    swatchColor: 'oklch(0.63 0.09 20)',
    label: 'Sky High\nMascara',
  },
  {
    id: 'elf-halo-glow-liquid-filter',
    name: 'Halo Glow Liquid Filter',
    brand: 'e.l.f.',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 14.96,
    tag: 'Best seller',
    rating: 4.5,
    reviews: 1600,
    short: 'Booster iluminador de acabado glow.',
    benefits: ['Glow', 'Complexion booster', 'Trend'],
    usage: 'Aplicar sola, debajo o mezclada con base.',
    ingredients: 'Base liquida cosmetica con pigmentos iluminadores.',
    warnings: 'Uso externo.',
    stock: 77,
    color: 'oklch(0.95 0.02 70)',
    swatchColor: 'oklch(0.80 0.05 70)',
    label: 'Halo Glow\nFilter',
  },
  {
    id: 'nars-radiant-creamy-concealer',
    name: 'Radiant Creamy Concealer',
    brand: 'NARS',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 25.22,
    rating: 4.5,
    reviews: 2100,
    short: 'Corrector de alta cobertura con acabado luminoso.',
    benefits: ['Cobertura', 'Luminoso', 'Iconico'],
    usage: 'Aplicar en ojeras o imperfecciones y difuminar.',
    ingredients: 'Base cremosa pigmentada para maquillaje.',
    warnings: 'Uso externo.',
    stock: 43,
    color: 'oklch(0.93 0.03 55)',
    swatchColor: 'oklch(0.72 0.09 55)',
    label: 'NARS\nConcealer',
  },
  {
    id: 'too-faced-better-than-sex-mascara',
    name: 'Better Than Sex Mascara',
    brand: 'Too Faced',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 29.00,
    rating: 4.4,
    reviews: 1900,
    short: 'Mascara de volumen muy conocida en Sephora.',
    benefits: ['Volumen', 'Pestanas', 'Popular'],
    usage: 'Aplicar en movimientos ascendentes.',
    ingredients: 'Base cosmetica y pigmentos.',
    warnings: 'Suspender si irrita.',
    stock: 52,
    color: 'oklch(0.91 0.04 350)',
    swatchColor: 'oklch(0.61 0.12 350)',
    label: 'Better Than\nSex',
  },
  {
    id: 'fenty-beauty-gloss-bomb-fenty-glow',
    name: 'Gloss Bomb Universal Lip Luminizer',
    brand: 'Fenty Beauty',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 28.95,
    rating: 4.7,
    reviews: 1700,
    short: 'Gloss labial brillante de la linea mas conocida de Fenty.',
    benefits: ['Brillo', 'Labios', 'Acabado universal'],
    usage: 'Aplicar directamente sobre los labios.',
    ingredients: 'Base gloss cosmetica y fragancia.',
    warnings: 'Uso externo.',
    stock: 59,
    color: 'oklch(0.92 0.04 15)',
    swatchColor: 'oklch(0.72 0.12 15)',
    label: 'Gloss Bomb\nFenty',
  },
  {
    id: 'olly-womens-multi',
    name: "Women's Multi",
    brand: 'OLLY',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 14.00,
    rating: 4.5,
    reviews: 620,
    short: 'Multivitaminico en gomitas para rutina diaria.',
    benefits: ['Multivitaminico', 'Gomitas', 'Uso diario'],
    usage: 'Tomar 2 gomitas al dia.',
    ingredients: 'Vitaminas esenciales, azucares y saborizantes.',
    warnings: 'No exceder la porcion recomendada.',
    stock: 73,
    color: 'oklch(0.93 0.05 355)',
    swatchColor: 'oklch(0.68 0.14 350)',
    label: 'OLLY\nWomen',
  },
  {
    id: 'smartypants-womens-formula',
    name: "Women's Formula Multi & Omegas",
    brand: 'SmartyPants',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 25.00,
    rating: 4.6,
    reviews: 540,
    short: 'Multivitaminico con omegas en formato gomita.',
    benefits: ['Multivitaminico', 'Omegas', 'Gomitas'],
    usage: 'Tomar la porcion diaria indicada en el empaque.',
    ingredients: 'Vitaminas, omegas y saborizantes naturales.',
    warnings: 'Guardar fuera del alcance de los ninos.',
    stock: 58,
    color: 'oklch(0.95 0.04 65)',
    swatchColor: 'oklch(0.76 0.12 60)',
    label: 'SmartyPants\nWomen',
  },
  {
    id: 'emergen-c-super-orange',
    name: 'Emergen-C 1000mg Vitamin C Powder Super Orange',
    brand: 'Emergen-C',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 14.00,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 880,
    short: 'Sobres efervescentes con vitamina C para uso diario.',
    benefits: ['Vitamina C', 'Sobres', 'Soporte diario'],
    usage: 'Disolver 1 sobre en agua.',
    ingredients: 'Vitamina C, complejo B y electrolitos.',
    warnings: 'Consumir una porcion al dia.',
    stock: 92,
    color: 'oklch(0.94 0.06 70)',
    swatchColor: 'oklch(0.74 0.16 65)',
    label: 'Emergen-C\nOrange',
  },
  {
    id: '21st-century-one-daily-womens',
    name: "One Daily Women's Tablets",
    brand: '21st Century',
    category: 'Vitaminas',
    need: 'Energía y vitaminas',
    price: 6.92,
    rating: 4.7,
    reviews: 255,
    short: 'Multivitaminico economico para uso diario.',
    benefits: ['Precio accesible', 'Rutina diaria', 'Vitaminas esenciales'],
    usage: 'Tomar 1 tableta al dia con comida.',
    ingredients: 'Vitaminas y minerales esenciales.',
    warnings: 'No exceder la dosis recomendada.',
    stock: 109,
    color: 'oklch(0.92 0.03 30)',
    swatchColor: 'oklch(0.66 0.11 25)',
    label: '21st Century\nWomen',
  },
  {
    id: 'culturelle-digestive-daily-probiotic',
    name: 'Digestive Daily Probiotic Capsules',
    brand: 'Culturelle',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 22.00,
    rating: 4.5,
    reviews: 460,
    short: 'Probiotico diario enfocado en salud digestiva.',
    benefits: ['Digestion', 'Probioticos', 'Uso diario'],
    usage: 'Tomar 1 capsula al dia con o sin alimentos.',
    ingredients: 'Lactobacillus rhamnosus GG y excipientes.',
    warnings: 'Guardar segun indicaciones del fabricante.',
    stock: 61,
    color: 'oklch(0.92 0.03 150)',
    swatchColor: 'oklch(0.58 0.08 155)',
    label: 'Culturelle\nDaily',
  },
  {
    id: 'orgain-organic-protein-superfoods-powder',
    name: 'Organic Protein + Superfoods Powder Creamy Chocolate Fudge',
    brand: 'Orgain',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 32.00,
    rating: 4.6,
    reviews: 510,
    short: 'Proteina vegetal con blend de superfoods.',
    benefits: ['Proteina vegetal', 'Superfoods', 'Smoothies'],
    usage: 'Mezclar 1 scoop con agua o bebida vegetal.',
    ingredients: 'Proteina vegetal organica y mezcla de superfoods.',
    warnings: 'Revisar alergenos del empaque.',
    stock: 47,
    color: 'oklch(0.88 0.05 55)',
    swatchColor: 'oklch(0.46 0.08 55)',
    label: 'Orgain\nProtein',
  },
  {
    id: 'lmnt-recharge-citrus-salt',
    name: 'Recharge Electrolyte Drink Mix Citrus Salt',
    brand: 'LMNT',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 45.00,
    tag: 'Premium',
    rating: 4.7,
    reviews: 390,
    short: 'Mezcla de electrolitos sin azucar para hidratacion.',
    benefits: ['Electrolitos', 'Sin azucar', 'Hidratacion'],
    usage: 'Disolver 1 sobre en agua fria.',
    ingredients: 'Sodio, potasio, magnesio y sabor natural.',
    warnings: 'Ajustar uso segun necesidades personales.',
    stock: 34,
    color: 'oklch(0.95 0.05 85)',
    swatchColor: 'oklch(0.74 0.15 80)',
    label: 'LMNT\nCitrus',
  },
  {
    id: 'vital-proteins-collagen-peptides-advanced',
    name: 'Collagen Peptides Advanced with Hyaluronic Acid & Vitamin C',
    brand: 'Vital Proteins',
    category: 'Suplementos',
    need: 'Energía y vitaminas',
    price: 30.00,
    rating: 4.6,
    reviews: 280,
    short: 'Version avanzada de colageno con acido hialuronico.',
    benefits: ['Colageno', 'Vitamina C', 'Acido hialuronico'],
    usage: 'Agregar 1 o 2 scoops a agua o smoothie.',
    ingredients: 'Peptidos de colageno, vitamina C, acido hialuronico.',
    warnings: 'Mantener en lugar fresco y seco.',
    stock: 38,
    color: 'oklch(0.95 0.03 90)',
    swatchColor: 'oklch(0.82 0.05 90)',
    label: 'Vital\nAdvanced',
  },
  {
    id: 'hero-cosmetics-mighty-patch-original',
    name: 'Mighty Patch Original Acne Pimple Patches',
    brand: 'Hero Cosmetics',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 12.99,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 2030,
    short: 'Parches hidrocoloides para granitos visibles.',
    benefits: ['Parches', 'Granitos', 'Uso puntual'],
    usage: 'Aplicar sobre piel limpia y seca durante varias horas.',
    ingredients: 'Parches hidrocoloides.',
    warnings: 'Uso externo.',
    stock: 120,
    color: 'oklch(0.96 0.02 80)',
    swatchColor: 'oklch(0.84 0.04 78)',
    label: 'Mighty\nPatch',
  },
  {
    id: 'paulas-choice-2-bha-liquid-exfoliant',
    name: 'Skin Perfecting 2% BHA Liquid Exfoliant',
    brand: "Paula's Choice",
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 35.00,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 1800,
    short: 'Exfoliante leave-on con acido salicilico.',
    benefits: ['BHA', 'Poros', 'Textura'],
    usage: 'Aplicar despues de limpiar la piel, sin enjuagar.',
    ingredients: 'Acido salicilico 2%, base liquida exfoliante.',
    warnings: 'Usar protector solar.',
    stock: 45,
    color: 'oklch(0.90 0.05 30)',
    swatchColor: 'oklch(0.56 0.14 30)',
    label: 'Paula\'s Choice\n2% BHA',
  },
  {
    id: 'the-ordinary-niacinamide-10-zinc-1',
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 7.00,
    rating: 4.5,
    reviews: 2200,
    short: 'Serum ligero para textura y brillo.',
    benefits: ['Niacinamida', 'Textura', 'Brillo'],
    usage: 'Aplicar antes de cremas, manana o noche.',
    ingredients: 'Niacinamida 10%, zinc 1%.',
    warnings: 'Uso externo.',
    stock: 133,
    color: 'oklch(0.93 0.02 210)',
    swatchColor: 'oklch(0.79 0.06 215)',
    label: 'Niacinamide\n+ Zinc',
  },
  {
    id: 'cerave-renewing-sa-cleanser',
    name: 'Renewing SA Cleanser',
    brand: 'CeraVe',
    category: 'Salud de la piel',
    need: 'Piel seca',
    price: 15.99,
    rating: 4.4,
    reviews: 980,
    short: 'Limpiador con acido salicilico para textura irregular.',
    benefits: ['SA', 'Limpieza', 'Textura'],
    usage: 'Masajear sobre piel humeda y enjuagar.',
    ingredients: 'Acido salicilico, ceramidas, niacinamida.',
    warnings: 'Evitar el area de ojos.',
    stock: 81,
    color: 'oklch(0.95 0.02 170)',
    swatchColor: 'oklch(0.72 0.06 180)',
    label: 'CeraVe\nSA Cleanser',
  },
  {
    id: 'vanicream-daily-facial-moisturizer',
    name: 'Daily Facial Moisturizer',
    brand: 'Vanicream',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 13.00,
    rating: 4.6,
    reviews: 430,
    short: 'Hidratante simple para piel sensible.',
    benefits: ['Piel sensible', 'Ligera', 'Sin fragancia'],
    usage: 'Aplicar sobre rostro limpio una o dos veces al dia.',
    ingredients: 'Humectantes suaves y escualano.',
    warnings: 'Uso externo.',
    stock: 69,
    color: 'oklch(0.96 0.01 200)',
    swatchColor: 'oklch(0.86 0.03 205)',
    label: 'Vanicream\nDaily',
  },
  {
    id: 'eucerin-advanced-repair-creme',
    name: 'Advanced Repair Creme',
    brand: 'Eucerin',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 15.00,
    rating: 4.6,
    reviews: 610,
    short: 'Crema nutritiva para piel seca y aspera.',
    benefits: ['Piel seca', 'Nutricion', 'Sin fragancia'],
    usage: 'Aplicar segun necesidad en rostro o cuerpo.',
    ingredients: 'Humectantes, ceramidas y emolientes.',
    warnings: 'Solo uso externo.',
    stock: 62,
    color: 'oklch(0.95 0.02 75)',
    swatchColor: 'oklch(0.84 0.04 75)',
    label: 'Eucerin\nRepair',
  },
  {
    id: 'first-aid-beauty-ultra-repair-cream',
    name: 'Ultra Repair Cream Intense Hydration',
    brand: 'First Aid Beauty',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 35.00,
    rating: 4.5,
    reviews: 1400,
    short: 'Crema conocida para piel muy seca y sensible.',
    benefits: ['Hidratacion intensa', 'Piel sensible', 'Barrera'],
    usage: 'Aplicar una o dos veces al dia.',
    ingredients: 'Avena coloidal, manteca de karite y emolientes.',
    warnings: 'Uso externo.',
    stock: 40,
    color: 'oklch(0.96 0.015 55)',
    swatchColor: 'oklch(0.84 0.05 55)',
    label: 'FAB\nUltra Repair',
  },
  {
    id: 'tatcha-the-dewy-skin-cream',
    name: 'The Dewy Skin Cream',
    brand: 'TATCHA',
    category: 'Hidratantes',
    need: 'Piel seca',
    price: 74.00,
    tag: 'Premium',
    rating: 4.6,
    reviews: 870,
    short: 'Crema premium de acabado luminoso.',
    benefits: ['Glow', 'Hidratacion', 'Premium'],
    usage: 'Aplicar una pequena cantidad al final de la rutina.',
    ingredients: 'Mezcla hidratante con extractos botanicos.',
    warnings: 'Uso externo.',
    stock: 18,
    color: 'oklch(0.95 0.03 330)',
    swatchColor: 'oklch(0.74 0.08 330)',
    label: 'TATCHA\nDewy',
  },
  {
    id: 'mustela-gentle-cleansing-gel',
    name: 'Gentle Cleansing Gel',
    brand: 'Mustela',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 21.00,
    rating: 4.6,
    reviews: 320,
    short: 'Gel suave para cabello y cuerpo del bebe.',
    benefits: ['Limpieza suave', 'Cabello y cuerpo', 'Uso diario'],
    usage: 'Aplicar sobre piel y cabello humedos, luego enjuagar.',
    ingredients: 'Base limpiadora suave de origen vegetal.',
    warnings: 'Evitar contacto con los ojos.',
    stock: 37,
    color: 'oklch(0.95 0.03 85)',
    swatchColor: 'oklch(0.84 0.06 80)',
    label: 'Mustela\nGel',
  },
  {
    id: 'boudreauxs-maximum-strength-butt-paste',
    name: "Maximum Strength Butt Paste",
    brand: "Boudreaux's",
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 9.00,
    rating: 4.7,
    reviews: 760,
    short: 'Pasta protectora para rozaduras por panal.',
    benefits: ['Rozaduras', 'Oxido de zinc', 'Proteccion'],
    usage: 'Aplicar sobre la zona limpia en cada cambio.',
    ingredients: 'Oxido de zinc y base emoliente.',
    warnings: 'Solo uso externo.',
    stock: 84,
    color: 'oklch(0.95 0.03 15)',
    swatchColor: 'oklch(0.82 0.08 15)',
    label: 'Boudreaux\'s\nPaste',
  },
  {
    id: 'aveeno-baby-eczema-therapy-nighttime-balm',
    name: 'Baby Eczema Therapy Nighttime Balm',
    brand: 'Aveeno Baby',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 17.00,
    rating: 4.6,
    reviews: 410,
    short: 'Balsamo nocturno para piel seca y con tendencia a eczema.',
    benefits: ['Eczema', 'Noche', 'Avena'],
    usage: 'Aplicar por la noche sobre zonas secas.',
    ingredients: 'Avena coloidal y emolientes.',
    warnings: 'Uso externo.',
    stock: 42,
    color: 'oklch(0.94 0.02 65)',
    swatchColor: 'oklch(0.82 0.05 65)',
    label: 'Aveeno Baby\nBalm',
  },
  {
    id: 'eucerin-baby-lotion',
    name: 'Baby Lotion Fragrance Free',
    brand: 'Eucerin Baby',
    category: 'Cuidado del bebé',
    need: 'Cuidado del bebé',
    price: 19.69,
    rating: 4.7,
    reviews: 669,
    short: 'Locion sin fragancia para piel delicada del bebe.',
    benefits: ['Sin fragancia', 'Piel sensible', 'Hidratacion'],
    usage: 'Aplicar segun necesidad despues del bano.',
    ingredients: 'Humectantes suaves y emolientes.',
    warnings: 'Solo uso topico.',
    stock: 39,
    color: 'oklch(0.96 0.01 205)',
    swatchColor: 'oklch(0.86 0.03 210)',
    label: 'Eucerin\nBaby',
  },
  {
    id: 'xtend-original-bcaa-blue-raspberry',
    name: 'XTEND Original BCAA Powder Blue Raspberry Ice',
    brand: 'XTEND',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 28.00,
    rating: 4.6,
    reviews: 590,
    short: 'BCAA en polvo para hidratacion y recuperacion.',
    benefits: ['BCAA', 'Recuperacion', 'Hidratacion'],
    usage: 'Mezclar con agua antes, durante o despues de entrenar.',
    ingredients: 'Aminoacidos de cadena ramificada y electrolitos.',
    warnings: 'Seguir porcion recomendada.',
    stock: 44,
    color: 'oklch(0.89 0.05 250)',
    swatchColor: 'oklch(0.52 0.12 250)',
    label: 'XTEND\nBCAA',
  },
  {
    id: 'premier-protein-chocolate-shake',
    name: 'Chocolate Protein Shake',
    brand: 'Premier Protein',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 10.00,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 1300,
    short: 'Batido listo para tomar con alto contenido de proteina.',
    benefits: ['Proteina', 'Listo para tomar', 'Conveniencia'],
    usage: 'Consumir frio como snack o despues de entrenar.',
    ingredients: 'Proteina lactea, vitaminas y minerales.',
    warnings: 'Contiene leche.',
    stock: 95,
    color: 'oklch(0.90 0.04 40)',
    swatchColor: 'oklch(0.48 0.06 40)',
    label: 'Premier\nProtein',
  },
  {
    id: 'legion-whey-plus',
    name: 'Whey+ Grass Fed Whey Protein Powder',
    brand: 'Legion',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 39.99,
    tag: 'Premium',
    rating: 4.8,
    reviews: 445,
    short: 'Proteina whey premium de vacas alimentadas con pasto.',
    benefits: ['Whey premium', 'Grass fed', 'Recuperacion'],
    usage: 'Mezclar 1 scoop con agua o leche.',
    ingredients: 'Whey isolate y saborizantes.',
    warnings: 'Contiene leche.',
    stock: 28,
    color: 'oklch(0.89 0.04 60)',
    swatchColor: 'oklch(0.54 0.10 60)',
    label: 'Legion\nWhey+',
  },
  {
    id: 'ascent-native-fuel-whey-protein',
    name: 'Native Fuel Whey Protein Blend Chocolate',
    brand: 'Ascent',
    category: 'Fitness',
    need: 'Fitness y recuperación',
    price: 34.99,
    rating: 4.6,
    reviews: 310,
    short: 'Proteina blend orientada a recuperacion deportiva.',
    benefits: ['Proteina', 'Chocolate', 'Post entreno'],
    usage: 'Mezclar 1 scoop con agua fria.',
    ingredients: 'Whey protein blend y cacao.',
    warnings: 'Contiene leche.',
    stock: 33,
    color: 'oklch(0.87 0.04 45)',
    swatchColor: 'oklch(0.42 0.07 45)',
    label: 'Ascent\nWhey',
  },
  {
    id: 'pepcid-ac-maximum-strength',
    name: 'Pepcid AC Maximum Strength Tablets',
    brand: 'Pepcid',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 19.00,
    rating: 4.6,
    reviews: 410,
    short: 'Alivio para acidez y reflujo ocasional.',
    benefits: ['Acidez', 'Reflujo', 'Alivio rapido'],
    usage: 'Usar segun las instrucciones del empaque.',
    ingredients: 'Famotidine.',
    warnings: 'No usar mas tiempo del indicado sin consultar medico.',
    stock: 58,
    color: 'oklch(0.92 0.03 230)',
    swatchColor: 'oklch(0.55 0.08 235)',
    label: 'Pepcid\nAC',
  },
  {
    id: 'voltaren-arthritis-pain-gel',
    name: 'Voltaren Arthritis Pain Gel',
    brand: 'Voltaren',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 18.00,
    rating: 4.6,
    reviews: 770,
    short: 'Gel topico para dolor localizado por artritis.',
    benefits: ['Topico', 'Dolor articular', 'Uso localizado'],
    usage: 'Aplicar segun instrucciones del empaque.',
    ingredients: 'Diclofenac sodium topical gel.',
    warnings: 'Solo uso externo.',
    stock: 49,
    color: 'oklch(0.94 0.03 190)',
    swatchColor: 'oklch(0.68 0.07 195)',
    label: 'Voltaren\nGel',
  },
  {
    id: 'claritin-24-hour-allergy',
    name: 'Claritin 24 Hour Allergy Tablets',
    brand: 'Claritin',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 18.99,
    rating: 4.7,
    reviews: 690,
    short: 'Antihistaminico para sintomas comunes de alergia.',
    benefits: ['Alergias', '24 horas', 'Uso diario'],
    usage: 'Seguir indicaciones del empaque.',
    ingredients: 'Loratadine.',
    warnings: 'Usar solo la dosis recomendada.',
    stock: 73,
    color: 'oklch(0.93 0.03 80)',
    swatchColor: 'oklch(0.69 0.09 80)',
    label: 'Claritin\n24H',
  },
  {
    id: 'imodium-a-d-caplets',
    name: 'A-D Anti-Diarrheal Caplets',
    brand: 'Imodium',
    category: 'Medicamentos',
    need: 'Energía y vitaminas',
    price: 9.99,
    rating: 4.6,
    reviews: 360,
    short: 'Caplets para control de diarrea ocasional.',
    benefits: ['Anti diarrea', 'Viajes', 'Uso ocasional'],
    usage: 'Usar segun instrucciones del empaque.',
    ingredients: 'Loperamide HCl.',
    warnings: 'No exceder la dosis indicada.',
    stock: 57,
    color: 'oklch(0.92 0.03 150)',
    swatchColor: 'oklch(0.58 0.08 150)',
    label: 'Imodium\nA-D',
  },
  {
    id: 'crest-3d-whitestrips-professional-effects',
    name: '3D Whitestrips Professional Effects',
    brand: 'Crest',
    category: 'Cuidado personal',
    need: 'Energía y vitaminas',
    price: 46.00,
    tag: 'Premium',
    rating: 4.5,
    reviews: 690,
    short: 'Tiras blanqueadoras para rutina dental en casa.',
    benefits: ['Blanqueamiento', 'Dental', 'Rutina en casa'],
    usage: 'Aplicar segun instrucciones del kit.',
    ingredients: 'Tiras dentales con agente blanqueador.',
    warnings: 'Usar solo en dientes.',
    stock: 32,
    color: 'oklch(0.96 0.01 220)',
    swatchColor: 'oklch(0.82 0.03 220)',
    label: 'Crest 3D\nWhite',
  },
  {
    id: 'dr-teals-lavender-epsom-salt',
    name: 'Pure Epsom Salt Soaking Solution Lavender',
    brand: "Dr Teal's",
    category: 'Cuidado personal',
    need: 'Piel seca',
    price: 7.00,
    rating: 4.7,
    reviews: 730,
    short: 'Sales de epsom para bano y relajacion corporal.',
    benefits: ['Bano', 'Relajacion', 'Lavanda'],
    usage: 'Disolver en agua tibia para remojo o bano.',
    ingredients: 'Sulfato de magnesio y fragancia de lavanda.',
    warnings: 'Solo uso externo.',
    stock: 84,
    color: 'oklch(0.93 0.04 300)',
    swatchColor: 'oklch(0.68 0.08 300)',
    label: 'Dr Teal\'s\nLavender',
  },
  {
    id: 'dr-bronners-peppermint-pure-castile-soap',
    name: 'Pure-Castile Liquid Soap Peppermint',
    brand: "Dr. Bronner's",
    category: 'Cuidado personal',
    need: 'Piel seca',
    price: 18.00,
    rating: 4.7,
    reviews: 560,
    short: 'Jabon liquido multiuso muy conocido de origen vegetal.',
    benefits: ['Multiuso', 'Peppermint', 'Origen vegetal'],
    usage: 'Diluir segun el uso deseado.',
    ingredients: 'Aceites saponificados y aceites esenciales.',
    warnings: 'Evitar ojos.',
    stock: 50,
    color: 'oklch(0.90 0.03 160)',
    swatchColor: 'oklch(0.54 0.06 165)',
    label: 'Dr Bronner\'s\nPeppermint',
  },
  {
    id: 'tree-hut-moroccan-rose-shea-sugar-scrub',
    name: 'Moroccan Rose Shea Sugar Scrub',
    brand: 'Tree Hut',
    category: 'Cuidado personal',
    need: 'Piel seca',
    price: 9.99,
    rating: 4.7,
    reviews: 860,
    short: 'Exfoliante corporal con aroma floral muy popular.',
    benefits: ['Exfoliacion', 'Cuerpo', 'Aroma floral'],
    usage: 'Aplicar sobre piel humeda y masajear antes de enjuagar.',
    ingredients: 'Azucar, manteca de karite y aceites.',
    warnings: 'Solo uso externo.',
    stock: 77,
    color: 'oklch(0.93 0.05 350)',
    swatchColor: 'oklch(0.70 0.12 350)',
    label: 'Tree Hut\nRose',
  },
  {
    id: 'billie-eilish-eilish-eau-de-parfum',
    name: 'Eilish Eau de Parfum',
    brand: 'Billie Eilish Fragrances',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 82.00,
    rating: 4.7,
    reviews: 430,
    short: 'Perfume gourmand dulce con fuerte presencia en retail.',
    benefits: ['Dulce', 'Gourmand', 'Popular'],
    usage: 'Aplicar en puntos de pulso.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable. Solo uso externo.',
    stock: 23,
    color: 'oklch(0.86 0.03 65)',
    swatchColor: 'oklch(0.50 0.08 65)',
    label: 'Eilish\nEDP',
  },
  {
    id: 'glossier-you-eau-de-parfum',
    name: 'Glossier You Eau de Parfum',
    brand: 'Glossier',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 78.00,
    rating: 4.6,
    reviews: 510,
    short: 'Fragancia limpia y personal de gran reconocimiento.',
    benefits: ['Clean scent', 'Uso diario', 'Versatil'],
    usage: 'Rociar sobre cuello y munecas.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable.',
    stock: 27,
    color: 'oklch(0.95 0.02 10)',
    swatchColor: 'oklch(0.82 0.05 10)',
    label: 'Glossier\nYou',
  },
  {
    id: 'valentino-donna-born-in-roma-eau-de-parfum',
    name: 'Donna Born In Roma Eau de Parfum',
    brand: 'Valentino',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 180.00,
    tag: 'Premium',
    rating: 4.8,
    reviews: 980,
    short: 'Perfume femenino floral ambarado muy vendido.',
    benefits: ['Floral', 'Premium', 'Larga duracion'],
    usage: 'Aplicar en puntos de pulso.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable. Uso externo.',
    stock: 16,
    color: 'oklch(0.90 0.04 330)',
    swatchColor: 'oklch(0.56 0.10 330)',
    label: 'Valentino\nRoma',
  },
  {
    id: 'ysl-libre-eau-de-parfum',
    name: 'Libre Eau de Parfum',
    brand: 'Yves Saint Laurent',
    category: 'Fragancias',
    need: 'Piel seca',
    price: 180.00,
    tag: 'Premium',
    rating: 4.6,
    reviews: 820,
    short: 'Fragancia floral aromatica muy conocida en Ulta.',
    benefits: ['Floral', 'Aromatica', 'Premium'],
    usage: 'Aplicar sobre cuello y munecas.',
    ingredients: 'Alcohol, agua, fragancia.',
    warnings: 'Inflamable.',
    stock: 15,
    color: 'oklch(0.95 0.03 75)',
    swatchColor: 'oklch(0.78 0.08 75)',
    label: 'YSL\nLibre',
  },
  {
    id: 'rare-beauty-soft-pinch-liquid-blush',
    name: 'Soft Pinch Liquid Blush',
    brand: 'Rare Beauty',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 24.00,
    tag: 'Best seller',
    rating: 4.7,
    reviews: 1600,
    short: 'Rubor liquido viral de acabado natural.',
    benefits: ['Rubor', 'Liquido', 'Natural'],
    usage: 'Aplicar pequenos puntos y difuminar rapido.',
    ingredients: 'Base liquida pigmentada.',
    warnings: 'Uso externo.',
    stock: 64,
    color: 'oklch(0.93 0.05 5)',
    swatchColor: 'oklch(0.72 0.12 5)',
    label: 'Rare Beauty\nBlush',
  },
  {
    id: 'nyx-fat-oil-lip-drip',
    name: 'Fat Oil Lip Drip',
    brand: 'NYX Professional Makeup',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 9.00,
    rating: 4.6,
    reviews: 920,
    short: 'Aceite labial brillante muy popular en retail.',
    benefits: ['Labios', 'Brillo', 'Hidratacion visual'],
    usage: 'Aplicar directamente sobre los labios.',
    ingredients: 'Base gloss con aceites cosmeticos.',
    warnings: 'Uso externo.',
    stock: 102,
    color: 'oklch(0.92 0.05 20)',
    swatchColor: 'oklch(0.74 0.14 20)',
    label: 'NYX\nFat Oil',
  },
  {
    id: 'elf-power-grip-primer',
    name: 'Power Grip Primer',
    brand: 'e.l.f. Cosmetics',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 11.00,
    tag: 'Best seller',
    rating: 4.6,
    reviews: 1340,
    short: 'Primer adherente de alto exito comercial.',
    benefits: ['Primer', 'Grip', 'Maquillaje de larga duracion'],
    usage: 'Aplicar antes de la base y dejar asentar.',
    ingredients: 'Base gel con agentes fijadores.',
    warnings: 'Uso externo.',
    stock: 89,
    color: 'oklch(0.94 0.03 145)',
    swatchColor: 'oklch(0.70 0.08 150)',
    label: 'Power Grip\nPrimer',
  },
  {
    id: 'nyx-butter-gloss',
    name: 'Butter Gloss Non-Sticky Lip Gloss',
    brand: 'NYX Professional Makeup',
    category: 'Maquillaje',
    need: 'Piel seca',
    price: 6.00,
    rating: 4.5,
    reviews: 1500,
    short: 'Gloss labial accesible y muy vendido.',
    benefits: ['Gloss', 'Labios', 'Precio accesible'],
    usage: 'Aplicar directamente sobre los labios.',
    ingredients: 'Base gloss cosmetica.',
    warnings: 'Uso externo.',
    stock: 145,
    color: 'oklch(0.92 0.04 5)',
    swatchColor: 'oklch(0.70 0.10 5)',
    label: 'NYX\nButter Gloss',
  },
].map((product) => ({
  ...product,
  imageUrl: `/products/${CATEGORY_FOLDER_BY_ID[product.category]}/${product.id}-1.jpg`,
  images: [
    { url: `/products/${CATEGORY_FOLDER_BY_ID[product.category]}/${product.id}-1.jpg`, alt: `${product.name} frente`, isPrimary: true },
    { url: `/products/${CATEGORY_FOLDER_BY_ID[product.category]}/${product.id}-2.jpg`, alt: `${product.name} angulo lateral` },
    { url: `/products/${CATEGORY_FOLDER_BY_ID[product.category]}/${product.id}-3.jpg`, alt: `${product.name} parte trasera` },
    { url: `/products/${CATEGORY_FOLDER_BY_ID[product.category]}/${product.id}-4.jpg`, alt: `${product.name} detalle` },
  ],
}));

const CATEGORIES = [
  { id: 'Vitaminas', label: 'Vitaminas', sub: 'Nutricion diaria', color: 'oklch(0.92 0.04 75)' },
  { id: 'Cuidado personal', label: 'Cuidado personal', sub: 'Rutina esencial', color: 'oklch(0.92 0.02 200)' },
  { id: 'Cuidado del bebé', label: 'Cuidado del bebé', sub: 'Delicado y seguro', color: 'oklch(0.95 0.02 85)' },
  { id: 'Suplementos', label: 'Suplementos', sub: 'Rendimiento total', color: 'oklch(0.9 0.04 140)' },
  { id: 'Salud de la piel', label: 'Salud de la piel', sub: 'Rutina avanzada', color: 'oklch(0.93 0.03 45)' },
  { id: 'Fitness', label: 'Fitness', sub: 'Energia y recuperacion', color: 'oklch(0.9 0.05 115)' },
  { id: 'Medicamentos', label: 'Medicamentos', sub: 'Botiquin de casa', color: 'oklch(0.93 0.02 200)' },
  { id: 'Hidratantes', label: 'Hidratantes', sub: 'Barrera reforzada', color: 'oklch(0.95 0.015 85)' },
  { id: 'Fragancias', label: 'Fragancias', sub: 'Aromas limpios', color: 'oklch(0.9 0.04 140)' },
  { id: 'Maquillaje', label: 'Maquillaje', sub: 'Toque natural', color: 'oklch(0.9 0.04 25)' },
];

async function seed() {
  await connectDB();
  await Product.deleteMany({});
  await Category.deleteMany({});
  await Product.insertMany(PRODUCTS);
  await Category.insertMany(CATEGORIES);
  console.log(`Seeded ${PRODUCTS.length} products and ${CATEGORIES.length} categories`);
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
